version: '3'

services:
  messy:
    build:
      context: .
      args:
        - PYTHON3_VERSION=${PYTHON3_VERSION}
    image: not4drugs/messy:0.0.1-alpha
    volumes:
      - ./messy/:/opt/messy/messy/
      - ./scripts/:/opt/messy/scripts/
      - ./tests/:/opt/messy/tests/
      - ./README.md:/opt/messy/README.md
      - ./setup.py:/opt/messy/setup.py
      - ./setup.cfg:/opt/messy/setup.cfg
    environment:
      - Messy.Name=messy
      - Messy.Host=messy
      - Messy.Port=63779
    command:
      - --verbose
      - run
    ports:
      - 63779:63779
    extra_hosts:
      - "dockerhost:${DOCKERHOST}"  # for debugging
