version: '3'

services:
  messy:
    build:
      context: .
      args:
        - PYTHON3_VERSION=${PYTHON3_VERSION}
    image: not4drugs/messy:0.0.0
    volumes:
      - ./messy/:/opt/messy/messy/
      - ./tests/:/opt/messy/tests/
      - ./README.md:/opt/messy/README.md
      - ./setup.py:/opt/messy/setup.py
      - ./setup.cfg:/opt/messy/setup.cfg
    entrypoint: python3
    command: setup.py test
    extra_hosts:
      - "dockerhost:$DOCKERHOST"  # for debugging
